baseURL: https://violetstead.com/
languageCode: en-us
title: Violet's Website

params:
  description: This is Violet Stead's website

markup:
  goldmark:
    renderer:
      unsafe: true

deployment:
  targets:
    - name: Azure
      URL: azblob://$web